---
development:
  cloud_name: matenalavo
  api_key: '253557542218282'
  api_secret: s7u2t54CsiiQqzG3wtDOf7xpgbk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: matenalavo
  api_key: '253557542218282'
  api_secret: s7u2t54CsiiQqzG3wtDOf7xpgbk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: matenalavo
  api_key: '253557542218282'
  api_secret: s7u2t54CsiiQqzG3wtDOf7xpgbk
  enhance_image_tag: true
  static_image_support: false
